# Generated by Django 2.0.5 on 2020-01-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_id',
            field=models.IntegerField(default=0),
        ),
    ]
